name: ${project.name}
version: ${project.version}
author: totemo
authors: [totemo]
description: ${project.description}
website: ${project.url}
main: io.totemo.lovedup.LovedUp
api-version: 1.13

permissions:
  lovedup.admin:
    description: Permission to administer the plugin.
    default: op

  lovedup.loveall:
    description: Permission to love everyone simultaneously.
    default: op

  lovedup.hateall:
    description: Permission to hate everyone simultaneously.
    default: op

  lovedup.love:
    description: Permission to love another player.
    default: true

  lovedup.hate:
    description: Permission to hate another player.
    default: true

  lovedup.exempt:
    description: Players with this permission do not show hearts or fireworks.
    default: false

commands:
  lovedup:
    description: Main plugin command.
    permission: lovedup.admin
    usage: |
    
      §e/<command> reload§f - Reload the configuration.
      §e/<command> debug§f - Toggle debug logging.

  loveall:
    description: Send love to all players.
    permission: lovedup.loveall
    usage: |
    
      §e/<command> <player>§f - Send your love, anonymously to everyone.

  sparkall:
    description: Send fireworks and a coloured message to all players.
    permission: lovedup.loveall
    usage: |
    
      §e/<command> §f[§e<message>§f] - Send fireworks and a coloured (by default pink) message to all players.

  hateall:
    description: Send hate to all players.
    permission: lovedup.hateall
    usage: |
    
      §e/<command> <player>§f - Send your hate, anonymously to everyone.

  growlall:
    description: Send hate and a coloured message to all players.
    permission: lovedup.hateall
    usage: |
    
      §e/<command> §f[§e<message>§f] - Send hate and a coloured message to all players.

  love:
    description: Send love to a player.
    permission: lovedup.love
    usage: |
    
      §e/<command> <player>§f - Send your love, anonymously to a player.

  hate:
    description: Send hate to a player.
    permission: lovedup.hate
    usage: |
    
      §e/<command> <player>§f - Send your hate, anonymously to a player.

  unlovable:
    description: Turn on or off receiving love (hearts, fireworks, messages).
    permission: lovedup.love
    aliases: [unloveable]
    usage: |
    
      §e/<command>§f - Turn on or off receiving love (hearts, fireworks, messages).

  unhateable:
    description: Turn on or off receiving hate (fire, evil, messages).
    permission: lovedup.hate
    aliases: [unhatable]
    usage: |
    
      §e/<command>§f - Turn on or off receiving hate (fire, evil, messages).
